                ; спрайт юнита А (вверх)
SolderA_Move_0_0:
                incbin "Sprites/Units/SolderA/Move/Move_0_0.spr"                ; 8x16
SolderA_Move_0_1:
                incbin "Sprites/Units/SolderA/Move/Move_0_1.spr"                ; 16x16
SolderA_Move_0_2:
                incbin "Sprites/Units/SolderA/Move/Move_0_2.spr"                ; 8x16
SolderA_Move_0_3:
                incbin "Sprites/Units/SolderA/Move/Move_0_3.spr"                ; 8x16

                ; спрайт юнита А (вверх-вправо)
SolderA_Move_1_0:
                incbin "Sprites/Units/SolderA/Move/Move_1_0.spr"                ; 16x16
SolderA_Move_1_1:
                incbin "Sprites/Units/SolderA/Move/Move_1_1.spr"                ; 16x16
SolderA_Move_1_2:
                incbin "Sprites/Units/SolderA/Move/Move_1_2.spr"                ; 16x16
SolderA_Move_1_3:
                incbin "Sprites/Units/SolderA/Move/Move_1_3.spr"                ; 16x16

                ; спрайт юнита А (вправо)
SolderA_Move_2_0:
                incbin "Sprites/Units/SolderA/Move/Move_2_0.spr"                ; 16x16
SolderA_Move_2_1:
                incbin "Sprites/Units/SolderA/Move/Move_2_1.spr"                ; 16x16
SolderA_Move_2_2:
                incbin "Sprites/Units/SolderA/Move/Move_2_2.spr"                ; 16x16
SolderA_Move_2_3:
                incbin "Sprites/Units/SolderA/Move/Move_2_3.spr"                ; 16x16

                ; спрайт юнита А (вправо-вниз)
SolderA_Move_3_0:
                incbin "Sprites/Units/SolderA/Move/Move_3_0.spr"                ; 8x16
SolderA_Move_3_1:
                incbin "Sprites/Units/SolderA/Move/Move_3_1.spr"                ; 8x16
SolderA_Move_3_2:
                incbin "Sprites/Units/SolderA/Move/Move_3_2.spr"                ; 8x16
SolderA_Move_3_3:
                incbin "Sprites/Units/SolderA/Move/Move_3_3.spr"                ; 8x16

                ; спрайт юнита А (вниз)
SolderA_Move_4_0:
                incbin "Sprites/Units/SolderA/Move/Move_4_0.spr"                ; 8x16
SolderA_Move_4_1:
                incbin "Sprites/Units/SolderA/Move/Move_4_1.spr"                ; 8x16
SolderA_Move_4_2:
                incbin "Sprites/Units/SolderA/Move/Move_4_2.spr"                ; 8x16
SolderA_Move_4_3:
                incbin "Sprites/Units/SolderA/Move/Move_4_3.spr"                ; 8x16

                ; спрайт юнита А (влево-вниз)
SolderA_Move_5_0:
                incbin "Sprites/Units/SolderA/Move/Move_5_0.spr"                ; 16x16
SolderA_Move_5_1:
                incbin "Sprites/Units/SolderA/Move/Move_5_1.spr"                ; 16x16
SolderA_Move_5_2:
                incbin "Sprites/Units/SolderA/Move/Move_5_2.spr"                ; 16x16
SolderA_Move_5_3:
                incbin "Sprites/Units/SolderA/Move/Move_5_3.spr"                ; 16x16

                ; спрайт юнита А (влево)
SolderA_Move_6_0:
                incbin "Sprites/Units/SolderA/Move/Move_6_0.spr"                ; 16x16
SolderA_Move_6_1:
                incbin "Sprites/Units/SolderA/Move/Move_6_1.spr"                ; 16x16
SolderA_Move_6_2:
                incbin "Sprites/Units/SolderA/Move/Move_6_2.spr"                ; 16x16
SolderA_Move_6_3:
                incbin "Sprites/Units/SolderA/Move/Move_6_3.spr"                ; 16x16

                ; спрайт юнита А (влево-вверх)
SolderA_Move_7_0:
                incbin "Sprites/Units/SolderA/Move/Move_7_0.spr"                ; 8x16
SolderA_Move_7_1:
                incbin "Sprites/Units/SolderA/Move/Move_7_1.spr"                ; 8x16
SolderA_Move_7_2:
                incbin "Sprites/Units/SolderA/Move/Move_7_2.spr"                ; 8x16
SolderA_Move_7_3:
                incbin "Sprites/Units/SolderA/Move/Move_7_3.spr"                ; 8x16
