
                ifndef _BUILDER_LANGUAGE_PACK_TEXT_MENU_ENGLISH_CONST_
                define _BUILDER_LANGUAGE_PACK_TEXT_MENU_ENGLISH_CONST_

NewGame         EQU 0x00
Continue        EQU 0x01
Options         EQU 0x02
Language        EQU 0x03
Russian         EQU 0x04
Spanish         EQU 0x05
English         EQU 0x06
Control         EQU 0x07
Kempston        EQU 0x08
Classic         EQU 0x09
Button_8        EQU 0x0A
Mouse           EQU 0x0B
LeftHanded      EQU 0x0C
RightHanded     EQU 0x0D
Keyboard        EQU 0x0E
Up              EQU 0x0F
Down            EQU 0x10
Left            EQU 0x11
Right           EQU 0x12
Select          EQU 0x13
Deselect        EQU 0x14
SpeedScroll     EQU 0x15
Menu            EQU 0x16
GameSpeed       EQU 0x17
Slow            EQU 0x18
Normal          EQU 0x19
Fast            EQU 0x1A
CursorSpeed     EQU 0x1B
Back            EQU 0x1C

                endif ; ~ _BUILDER_LANGUAGE_PACK_TEXT_MENU_ENGLISH_CONST_

