
                ifndef _BUILDER_LANGUAGE_PACK_TEXT_MENU_ENGLISH_CONST_
                define _BUILDER_LANGUAGE_PACK_TEXT_MENU_ENGLISH_CONST_

NewGame         EQU 0x00
Continue        EQU 0x01
Options         EQU 0x02
Language        EQU 0x03
Russian         EQU 0x04
Spanish         EQU 0x05
English         EQU 0x06
Control         EQU 0x07
MouseSel        EQU 0x08
KempstonSel     EQU 0x09
KeyboardSel     EQU 0x0A
Kempston        EQU 0x0B
Classic         EQU 0x0C
Button_8        EQU 0x0D
Mouse           EQU 0x0E
LeftHanded      EQU 0x0F
RightHanded     EQU 0x10
Keyboard        EQU 0x11
Up              EQU 0x12
Down            EQU 0x13
Left            EQU 0x14
Right           EQU 0x15
Select          EQU 0x16
Deselect        EQU 0x17
SpeedScroll     EQU 0x18
MenuPause       EQU 0x19
GameSpeed       EQU 0x1A
Slow            EQU 0x1B
Normal          EQU 0x1C
Fast            EQU 0x1D
CursorSpeed     EQU 0x1E
Audio           EQU 0x1F
Audio_AY        EQU 0x20
Audio_GS        EQU 0x21
Graphics        EQU 0x22
Graphic_Low     EQU 0x23
Graphic_Medium  EQU 0x24
Graphic_High    EQU 0x25

Back            EQU 0x26
Apply           EQU 0x27

KEY_CAPS_SHIFT  EQU 0x28
KEY_Z           EQU 0x29
KEY_X           EQU 0x2A
KEY_C           EQU 0x2B
KEY_V           EQU 0x2C

KEY_A           EQU 0x2D
KEY_S           EQU 0x2E
KEY_D           EQU 0x2F
KEY_F           EQU 0x30
KEY_G           EQU 0x31

KEY_Q           EQU 0x32
KEY_W           EQU 0x33
KEY_E           EQU 0x34
KEY_R           EQU 0x35
KEY_T           EQU 0x36

KEY_1           EQU 0x37
KEY_2           EQU 0x38
KEY_3           EQU 0x39
KEY_4           EQU 0x3A
KEY_5           EQU 0x3B

KEY_6           EQU 0x3C
KEY_7           EQU 0x3D
KEY_8           EQU 0x3E
KEY_9           EQU 0x3F
KEY_0           EQU 0x40

KEY_Y           EQU 0x41
KEY_U           EQU 0x42
KEY_I           EQU 0x43
KEY_O           EQU 0x44
KEY_P           EQU 0x45

KEY_H           EQU 0x46
KEY_J           EQU 0x47
KEY_K           EQU 0x48
KEY_L           EQU 0x49
KEY_ENTER       EQU 0x4A

KEY_B           EQU 0x4B
KEY_N           EQU 0x4C
KEY_M           EQU 0x4D
KEY_SYM_SHIFT   EQU 0x4E
KEY_SPACE       EQU 0x4F

KEY_NONE        EQU 0x50 - KEY_CAPS_SHIFT
KEY_INPUT       EQU 0x51 - KEY_CAPS_SHIFT

                endif ; ~ _BUILDER_LANGUAGE_PACK_TEXT_MENU_ENGLISH_CONST_

