
                ifndef _BUILDER_LANGUAGE_PACK_TEXT_MENU_ENGLISH_CONST_
                define _BUILDER_LANGUAGE_PACK_TEXT_MENU_ENGLISH_CONST_

NewGame         EQU 0x00
Continue        EQU 0x01
Options         EQU 0x02
Language        EQU 0x03
Russian         EQU 0x04
Spanish         EQU 0x05
English         EQU 0x06
Control         EQU 0x07
MouseSel        EQU 0x08
KempstonSel     EQU 0x09
KeyboardSel     EQU 0x0A
Kempston        EQU 0x0B
Classic         EQU 0x0C
Button_8        EQU 0x0D
Mouse           EQU 0x0E
LeftHanded      EQU 0x0F
RightHanded     EQU 0x10
Keyboard        EQU 0x11
Up              EQU 0x12
Down            EQU 0x13
Left            EQU 0x14
Right           EQU 0x15
Select          EQU 0x16
Deselect        EQU 0x17
SpeedScroll     EQU 0x18
MenuPause       EQU 0x19
GameSpeed       EQU 0x1A
Slow            EQU 0x1B
Normal          EQU 0x1C
Fast            EQU 0x1D
CursorSpeed     EQU 0x1E
Back            EQU 0x1F

KEY_CAPS_SHIFT  EQU 0x20
KEY_Z           EQU 0x21
KEY_X           EQU 0x22
KEY_C           EQU 0x23
KEY_V           EQU 0x24

KEY_A           EQU 0x25
KEY_S           EQU 0x26
KEY_D           EQU 0x27
KEY_F           EQU 0x28
KEY_G           EQU 0x29

KEY_Q           EQU 0x2A
KEY_W           EQU 0x2B
KEY_E           EQU 0x2C
KEY_R           EQU 0x2D
KEY_T           EQU 0x2E

KEY_1           EQU 0x2F
KEY_2           EQU 0x30
KEY_3           EQU 0x31
KEY_4           EQU 0x32
KEY_5           EQU 0x33

KEY_6           EQU 0x34
KEY_7           EQU 0x35
KEY_8           EQU 0x36
KEY_9           EQU 0x37
KEY_0           EQU 0x38

KEY_Y           EQU 0x39
KEY_U           EQU 0x3A
KEY_I           EQU 0x3B
KEY_O           EQU 0x3C
KEY_P           EQU 0x3D

KEY_H           EQU 0x3E
KEY_J           EQU 0x3F
KEY_K           EQU 0x40
KEY_L           EQU 0x41
KEY_ENTER       EQU 0x42

KEY_B           EQU 0x43
KEY_N           EQU 0x44
KEY_M           EQU 0x45
KEY_SYM_SHIFT   EQU 0x46
KEY_SPACE       EQU 0x47

                endif ; ~ _BUILDER_LANGUAGE_PACK_TEXT_MENU_ENGLISH_CONST_

