
                ifndef _BUILDER_INCLUDES_
                define _BUILDER_INCLUDES_

                include "Macro/Include.inc"
                include "Config/Include.inc"
                include "Const/Include.inc"
                include "Struct/Include.inc"

                ; version build
                define BUILD 1
                define MAJOR 1
                define MINOR 3

                define TRD_FILENAME "Torn Metal.trd"                            ; имя образа TRD

                endif ; ~_BUILDER_INCLUDES_
