
                ifndef _CORE_DISPLAY_METODS_RESTORE_INCLUDE_
                define _CORE_DISPLAY_METODS_RESTORE_INCLUDE_

                module Metod

                ; ---------- 16 ----------
                include "R_16_0.asm"
                include "R_16_0_Shift.asm"
                include "R_16_0_LeftShift.asm"
                include "R_16_0_RightShift.asm"
                include "R_16_1_Left.asm"
                include "R_16_1_Right.asm"
                include "R_16_1_LeftShift.asm"
                include "R_16_1_RightShift.asm"

                endmodule

                endif ; ~_CORE_DISPLAY_METODS_RESTORE_INCLUDE_
