;   000 - 1A (первый тир, нейтрального шаттла)
                FCompositeSpriteInfo CSIF_SIZE_32 | CSIF_OR_XOR | CSIF_ANIM_2, ANIM_INDEX_0,       16, -16,  16, -16
                incbin "Core/Module/Sprites/Shuttle/1A/Shuttle_1A_0_0.spr"
                incbin "Core/Module/Sprites/Shuttle/1A/Shuttle_1A_0_1.spr"

                FCompositeSpriteInfo CSIF_SIZE_32 | CSIF_OR_XOR | CSIF_ANIM_NONE, ANIM_INDEX_NONE, 16, -16,  16,   0
                incbin "Core/Module/Sprites/Shuttle/1A/Shuttle_1A_1.spr"

                FCompositeSpriteInfo CSIF_SIZE_32 | CSIF_OR_XOR | CSIF_ANIM_2, ANIM_INDEX_0,       16, -16,  16,  16
                incbin "Core/Module/Sprites/Shuttle/1A/Shuttle_1A_2_0.spr"
                incbin "Core/Module/Sprites/Shuttle/1A/Shuttle_1A_2_1.spr"

                FCompositeSpriteInfo CSIF_SIZE_32 | CSIF_OR_XOR | CSIF_ANIM_NONE, ANIM_INDEX_NONE, 16,   0,  16, -16
                incbin "Core/Module/Sprites/Shuttle/1A/Shuttle_1A_3.spr"

                FCompositeSpriteInfo CSIF_SIZE_32 | CSIF_OR | CSIF_ANIM_NONE, ANIM_INDEX_NONE      16,   0,  16,   0
                incbin "Core/Module/Sprites/Shuttle/1A/Shuttle_1A_4.spr"

                FCompositeSpriteInfo CSIF_SIZE_32 | CSIF_OR_XOR | CSIF_ANIM_NONE, ANIM_INDEX_NONE, 16,   0,  16,  16
                incbin "Core/Module/Sprites/Shuttle/1A/Shuttle_1A_5.spr"

                FCompositeSpriteInfo CSIF_SIZE_32 | CSIF_OR_XOR | CSIF_ANIM_5,  ANIM_INDEX_1,      16,  16,  16, -16
                incbin "Core/Module/Sprites/Shuttle/1A/Shuttle_1A_6.spr"
                incbin "Core/Module/Sprites/Shuttle/1A/Shuttle_1A_6_3.spr"
                incbin "Core/Module/Sprites/Shuttle/1A/Shuttle_1A_6_2.spr"
                incbin "Core/Module/Sprites/Shuttle/1A/Shuttle_1A_6_1.spr"
                incbin "Core/Module/Sprites/Shuttle/1A/Shuttle_1A_6_0.spr"

                FCompositeSpriteInfo CSIF_SIZE_32 | CSIF_OR_XOR | CSIF_ANIM_NONE, ANIM_INDEX_NONE, 16,  16,  16,   0
                incbin "Core/Module/Sprites/Shuttle/1A/Shuttle_1A_7.spr"

                FCompositeSpriteInfo CSIF_SIZE_32 | CSIF_OR_XOR | CSIF_ANIM_5,  ANIM_INDEX_1,      16,  16,  16,  16
                incbin "Core/Module/Sprites/Shuttle/1A/Shuttle_1A_8.spr"
                incbin "Core/Module/Sprites/Shuttle/1A/Shuttle_1A_8_3.spr"
                incbin "Core/Module/Sprites/Shuttle/1A/Shuttle_1A_8_2.spr"
                incbin "Core/Module/Sprites/Shuttle/1A/Shuttle_1A_8_1.spr"
                incbin "Core/Module/Sprites/Shuttle/1A/Shuttle_1A_8_0.spr"

                DB #00                                                          ; завершение
