
                    ifndef _COLOR_INCLUDE_
                    define _COLOR_INCLUDE_

BLACK               EQU 0
BLUE                EQU 1
RED                 EQU 2
MAGENTA             EQU 3
GREEN               EQU 4
CYAN                EQU 5
YELLOW              EQU 6
WHITE               EQU 7
BRIGHT              EQU %01000000
FLASH               EQU %10000000



                    endif ; ~_COLOR_INCLUDE_