
                ifndef _CORE_MODULE_AI_COMPOSITE_INCLUDE_
                define _CORE_MODULE_AI_COMPOSITE_INCLUDE_

                include "Definition.inc"
                
                module Composite
                
                include "Selector.inc"
                include "Sequence.inc"
                include "Task.inc"

                endmodule

                include "Handler.asm"

                endif ; ~ _CORE_MODULE_AI_COMPOSITE_INCLUDE_