
                ifndef _CORE_MODULE_AI_COMPOSITE_INCLUDE_
                define _CORE_MODULE_AI_COMPOSITE_INCLUDE_

                include "Definition.inc"
                include "Handler.asm"

                ; module Composite
                
                ; include "Selector.inc"
                ; include "Sequence.inc"
                ; include "Task.inc"

                ; endmodule

                endif ; ~ _CORE_MODULE_AI_COMPOSITE_INCLUDE_