
                ifndef _CORE_MODULE_UNIT_SELECT_INCLUDE_
                define _CORE_MODULE_UNIT_SELECT_INCLUDE_

                module Select

                include "SelectedRect.asm"
                include "AddUnitsToQueue.asm"
                include "TargetDefinition.asm"
                include "SelectedUnit.asm"

                endmodule

                endif ; ~ _CORE_MODULE_UNIT_SELECT_INCLUDE_