
                    ifndef _STRUCTURE_BEHAVIOR_TREE_
                    define _STRUCTURE_BEHAVIOR_TREE_

                    struct FBehaviorTree
Index               DB #00                                                      ; индекс потомка
State               DB #00                                                      ; состояние поведения
                    ends

                    endif ; ~_STRUCTURE_BEHAVIOR_TREE_