
                ifndef _STRUCTURES_INCLUDE_
                define _STRUCTURES_INCLUDE_

                include "Base.inc"
                include "Map.inc"
                include "Render.inc"
                include "Sprite.inc"
                include "UnitInfo.inc"
                include "Input.inc"
                include "SurfaceProperty.inc"

                endif ; ~_STRUCTURES_INCLUDE_