
                ifndef _MODULE_GAME_INCLUDE_
                define _MODULE_GAME_INCLUDE_

                include "EntryPoint.asm"
                include "Loop.asm"
                include "Interrupt.asm"
                include "Initialize/Include.inc"
                include "Render/Include.inc"
                include "Input/Include.inc"
                include "Tilemap/Include.inc"

                endif ; ~_MODULE_GAME_INCLUDE_
