
                ifndef _CORE_MODULE_MENU_MAIN_SCREENSAVER_INCLUDE_
                define _CORE_MODULE_MENU_MAIN_SCREENSAVER_INCLUDE_

                module Screensaver

                include "Begin.asm"
                include "Timeline.asm"
                include "Core/Module/VFX/Stars/Include.inc"

Flags:          DB #00

                endmodule

                endif ; ~ _CORE_MODULE_MENU_MAIN_SCREENSAVER_INCLUDE_
