
                ifndef _CONST_FILES_NAME_
                define _CONST_FILES_NAME_

                define SystemExt         '#'
                
                define BootNameTRD       "boot.B"
                
                define KernelName        "Kernel"
                define KernelNameTRD     "Kernel.#"
                
                define FileSystemName    "FS"
                define FileSystemNameTRD "FS.#"
                
                define LoaderName        "Loader"                               ; имя загрузчика
                define LoaderNameTRD     "Loader.#"                             ; имя загрузчика
                
                define MainMenuName      "Main"                                 ; имя главного меню
                define MainMenuNameTRD   "Main.#"                               ; имя главного меню

                endif ; ~_CONST_FILES_NAME_
