
                ifndef _CONST_FILES_NAME_
                define _CONST_FILES_NAME_

                define SystemExt         '#'
                define GraphicsExt       'D'
                
                define BootNameTRD       "boot.B"
                
                define KernelName        "Kernel"
                define KernelNameTRD     "Kernel.#"
                
                define FileSystemName    "FS"
                define FileSystemNameTRD "FS.#"
                
                define LoaderName        "Loader"                               ; имя загрузчика
                define LoaderNameTRD     "Loader.#"                             ; имя загрузчика

                define LanguageName      "Language"                             ; имя модуля языка
                define LanguageNameTRD   "Language.#"                           ; имя модуля языка

                ; fonts
                define FontRuName        "Font Ru"                              ; имя шрифта русского языка
                define FontRuNameTRD     "Font Ru.#"                            ; имя шрифта русского языка
                define FontSpName        "Font Sp"                              ; имя шрифта испанского языка
                define FontSpNameTRD     "Font Sp.#"                            ; имя шрифта испанского языка
                define FontEnName        "Font En"                              ; имя шрифта английского языка
                define FontEnNameTRD     "Font En.#"                            ; имя шрифта английского языка

                ; text
                define MenuTextRuName       "Menu Ru"                           ; имя файла русского языка меню
                define MenuTextRuNameTRD    "Menu Ru.#"                         ; имя файла русского языка меню
                define MenuTextSpName       "Menu Sp"                           ; имя файла испанского языка меню
                define MenuTextSpNameTRD    "Menu Sp.#"                         ; имя файла испанского языка меню
                define MenuTextEnName       "Menu En"                           ; имя файла английского языка меню
                define MenuTextEnNameTRD    "Menu En.#"                         ; имя файла английского языка меню
                
                define MenuCoreName         "M.Core"                            ; имя файла основных функций работы с меню
                define MenuCoreNameTRD      "M.Core.#"                          ; имя файла основных функций работы с меню

                define MenuMainName         "M.Main"                            ; имя файла "главного меню"
                define MenuMainNameTRD      "M.Main.#"                          ; имя файла "главного меню"

                define MenuOptionsName      "M.Option"                          ; имя файла "меню настроек"
                define MenuOptionsNameTRD   "M.Option.#"                        ; имя файла "меню настроек"

                define MenuNewGameName      "M.NGame"                           ; имя файла "меню новая игры"
                define MenuNewGameNameTRD   "M.NGame.#"                         ; имя файла "меню новая игры"

                define MenuNewGameGraphicsAName     "M.NGameA"                  ; имя файла графики для меню
                define MenuNewGameGraphicsANameTRD  "M.NGameA.D"                ; имя файла графики для меню

                endif ; ~_CONST_FILES_NAME_
