
                ifndef _CONST_HARDWARE_RESTRICTION_
                define _CONST_HARDWARE_RESTRICTION_
HW_MOUSE_BIT    EQU 0x00                                                        ; флаг, не доступности кемстон мыши
HW_JOY_8_BIT    EQU 0x01                                                        ; флаг, не доступности кемстон джойстика на 8 кнопок

                endif ; ~_CONST_HARDWARE_RESTRICTION_
