
                ifndef _CONST_INCLUDES_
                define _CONST_INCLUDES_

                include "Config.inc"
                include "Color.inc"
                include "GameScreen.inc"
                include "Frame.inc"
                include "Gameplay.inc"
                include "Hardware.inc"
                include "Input.inc"

                include "Interrupt.inc"
                include "FileSystem.inc"
                include "Loader.inc"

                include "Memory.inc"
                include "MemoryMap.inc"
                include "GameMM.inc"

                include "SharedBuffer.inc"
                include "RenderBuffer.inc"
                include "TilemapBuffer.inc"

                include "Language.inc"
                include "Tilemap.inc"

                include "MainMenu.inc"
                include "Dialog.inc"

                include "FilesName.inc"

                endif ; ~_CONST_INCLUDES_
