
                ifndef _CONST_INCLUDES_
                define _CONST_INCLUDES_

                include "Color.inc"
                include "Frame.inc"
                include "Gameplay.inc"
                include "Hardware.inc"
                include "Input.inc"
                include "Buffer.inc"
                include "FileSystem.inc"
                include "Interrupt.inc"
                include "FilesName.inc"
                include "Loader.inc"
                include "MainMenu.inc"
                include "SharedMemoryMap.inc"
                include "MemoryMap.inc"

                endif ; ~_CONST_INCLUDES_
