
                ifndef _CONST_STRUCTURE_UNIT_RANK_
                define _CONST_STRUCTURE_UNIT_RANK_

RANK_ROOKIE         EQU 0x00                                                    ; новобранец
RANK_TRAINED        EQU 0x01                                                    ; тренированный
RANK_REGULAR        EQU 0x02                                                    ; опытный
RANK_PROFESSIONAL   EQU 0x03                                                    ; профессионал
RANK_VETERAN        EQU 0x04                                                    ; ветеран
RANK_ELITE          EQU 0x05                                                    ; элитный
RANK_SPECIAL        EQU 0x06                                                    ; специалист
RANK_HERO           EQU 0x07                                                    ; герой

                endif ; ~_CONST_STRUCTURE_UNIT_RANK_
