
                ifndef _CORE_MODULE_INCLUDE_
                define _CORE_MODULE_INCLUDE_

                include "Utils/Include.inc"
                include "AI/Include.inc"
                include "Animation/Include.inc"
                include "Pathfinding/Include.inc"
                include "Spawn/Include.inc"
                include "Unit/Include.inc"

                include "SFX/Include.inc"
                include "VFX/Include.inc"

                endif ; ~_CORE_MODULE_INCLUDE_
