
                ifndef _CORE_MODULE_DRAW_SPRITE_DRAW_FUNCTION_INCLUDE_
                define _CORE_MODULE_DRAW_SPRITE_DRAW_FUNCTION_INCLUDE_

                module Function

                include "Shift_LD.asm"
                include "Shift_OR_XOR.asm"
                include "NoShift_LD.asm"
                include "NoShift_OR_XOR.asm"

                endmodule

                endif ; ~ _CORE_MODULE_DRAW_SPRITE_DRAW_FUNCTION_INCLUDE_
