InfantrySprite:
                ; Move

._0_0_1         ; t - 0 (), d - 0 (up), s - 1 (move)
                FSprite 16-2,     8-1+4,      1,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_0_3   ; напровление 0, индекс анимации 3
                FSprite 16-2,     8-1+4,      1,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_0_2   ; напровление 0, индекс анимации 2
                FSprite 16-2,     8-1+4,      2,     12,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_0_1   ; напровление 0, индекс анимации 1
                FSprite 16-2,     8-1+4,      1,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_0_0   ; напровление 0, индекс анимации 0

._0_1_1         ; t - 0 (), d - 1 (up-right), s - 1 (move)
                FSprite 16-2,     8-1+4,      2,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_1_3   ; напровление 1, индекс анимации 3
                FSprite 16-2,     8-1+4,      2,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_1_2   ; напровление 1, индекс анимации 2
                FSprite 16-4,     8-1+4,      2,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_1_1   ; напровление 1, индекс анимации 1
                FSprite 16-2,     8-1+4,      2,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_1_0   ; напровление 1, индекс анимации 0

._0_2_1         ; t - 0 (), d - 2 (right), s - 1 (move)
                FSprite 16-2,     8-1+4,      2,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_2_3   ; напровление 2, индекс анимации 3
                FSprite 16-2,     8-1+4,      2,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_2_2   ; напровление 2, индекс анимации 2
                FSprite 16-2,     8-1+4,      2,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_2_1   ; напровление 2, индекс анимации 1
                FSprite 16-2,     8-1+4,      2,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_2_0   ; напровление 2, индекс анимации 0

._0_3_1         ; t - 0 (), d - 3 (down-right), s - 1 (move)
                FSprite 16-2,     8-1+4,      1,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_3_3   ; напровление 3, индекс анимации 3
                FSprite 16-2,     8-1+4,      1,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_3_2   ; напровление 3, индекс анимации 2
                FSprite 16-2,     8-1+4,      1,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_3_1   ; напровление 3, индекс анимации 1
                FSprite 16-2,     8-1+4,      1,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_3_0   ; напровление 3, индекс анимации 0

._0_4_1         ; t - 0 (), d - 4 (down), s - 1 (move)
                FSprite 16-2,     8-1+4,      1,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_4_3   ; напровление 4, индекс анимации 3
                FSprite 16-2,     8-1+4,      1,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_4_2   ; напровление 4, индекс анимации 2
                FSprite 16-2,     8-1+4,      1,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_4_1   ; напровление 4, индекс анимации 1
                FSprite 16-2,     8-1+4,      1,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_4_0   ; напровление 4, индекс анимации 0

._0_5_1         ; t - 0 (), d - 5 (down-left), s - 1 (move)
                FSprite 16-2,     8-1+4,      2,     12,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_5_3   ; напровление 5, индекс анимации 3
                FSprite 16-2,     8-1+4,      2,     12,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_5_2   ; напровление 5, индекс анимации 2
                FSprite 16-2,     8-1+4,      2,     12,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_5_1   ; напровление 5, индекс анимации 1
                FSprite 16-2,     8-1+4,      2,     12,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_5_0   ; напровление 5, индекс анимации 0

._0_6_1         ; t - 0 (), d - 6 (left), s - 1 (move)
                FSprite 16-2,     8-1+4,      2,     12,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_6_3   ; напровление 6, индекс анимации 3
                FSprite 16-2,     8-1+4,      2,     12,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_6_2   ; напровление 6, индекс анимации 2
                FSprite 16-2,     8-1+4,      2,     12,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_6_1   ; напровление 6, индекс анимации 1
                FSprite 16-2,     8-1+4,      2,     12,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_6_0   ; напровление 6, индекс анимации 0

._0_7_1         ; t - 0 (), d - 7 (up-left), s - 1 (move)
                FSprite 16-2,     8-1+4,      1,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_7_3   ; напровление 7, индекс анимации 3
                FSprite 16-2,     8-1+4,      1,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_7_2   ; напровление 7, индекс анимации 2
                FSprite 16-4,     8-1+4,      1,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_7_1   ; напровление 7, индекс анимации 1
                FSprite 16-2,     8-1+4,      1,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_7_0   ; напровление 7, индекс анимации 0

                ; Attack

._0_0_2         ; t - 0 (), d - 0 (up), s - 2 (attack)
                FSprite 18,     15,      2,     11,      0, PageSprites_0,    MemoryPage_4.SolderA_Attack_0_1      ; напровление 0, индекс анимации 1
                FSprite 18,     14,      2,     11,      0, PageSprites_0,    MemoryPage_4.SolderA_Attack_0_0      ; напровление 0, индекс анимации 0

._0_1_2         ; t - 0 (), d - 1 (up-right), s - 1 (move)
                FSprite 14,     12,      2,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Attack_1_1      ; напровление 1, индекс анимации 1
                FSprite 14,     11,      2,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Attack_1_0      ; напровление 1, индекс анимации 0

._0_2_2         ; t - 0 (), d - 2 (right), s - 2 (attack)
                FSprite 14,     10,      3,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Attack_2_1      ; напровление 2, индекс анимации 1
                FSprite 14,     10,      3,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Attack_2_0      ; напровление 2, индекс анимации 0

._0_3_2         ; t - 0 (), d - 3 (down-right), s - 2 (attack)
                FSprite 14,     10,      2,      5,      0, PageSprites_0,    MemoryPage_4.SolderA_Attack_3_1      ; напровление 3, индекс анимации 1
                FSprite 16,     10,      2,      5,      0, PageSprites_0,    MemoryPage_4.SolderA_Attack_3_0      ; напровление 3, индекс анимации 0

._0_4_2         ; t - 0 (), d - 4 (down), s - 2 (attack)
                FSprite 16,     10,      2,      5,      0, PageSprites_0,    MemoryPage_4.SolderA_Attack_4_1      ; напровление 4, индекс анимации 1
                FSprite 18,     10,      2,      5,      0, PageSprites_0,    MemoryPage_4.SolderA_Attack_4_0      ; напровление 4, индекс анимации 0

._0_5_2         ; t - 0 (), d - 5 (down-left), s - 2 (attack)
                FSprite 14,     10,      2,     12,      0, PageSprites_0,    MemoryPage_4.SolderA_Attack_5_1      ; напровление 5, индекс анимации 1
                FSprite 14,     10,      2,     12,      0, PageSprites_0,    MemoryPage_4.SolderA_Attack_5_0      ; напровление 5, индекс анимации 0

._0_6_2         ; t - 0 (), d - 6 (left), s - 2 (attack)
                FSprite 14,     10,      3,     20,      0, PageSprites_0,    MemoryPage_4.SolderA_Attack_6_1      ; напровление 6, индекс анимации 1
                FSprite 14,     10,      3,     20,      0, PageSprites_0,    MemoryPage_4.SolderA_Attack_6_0      ; напровление 6, индекс анимации 0

._0_7_2         ; t - 0 (), d - 7 (up-left), s - 2 (attack)
                FSprite 16,     14,      2,     12,      0, PageSprites_0,    MemoryPage_4.SolderA_Attack_7_1       ; напровление 7, индекс анимации 1
                FSprite 18,     15,      2,     12,      0, PageSprites_0,    MemoryPage_4.SolderA_Attack_7_0       ; напровление 7, индекс анимации 0

                ; Dead

._0_0_3         ; t - 0 (), d - 0 (up), s - 3 (dead) !
                FSprite  8,      7,      2,      6,      0, PageSprites_0,    MemoryPage_4.SolderA_Dead_0_3         ; напровление 0, индекс анимации 3
                FSprite 10,      8,      2,      5,      0, PageSprites_0,    MemoryPage_4.SolderA_Dead_0_2         ; напровление 0, индекс анимации 2
                FSprite 12,     10,      2,      5,      0, PageSprites_0,    MemoryPage_4.SolderA_Dead_0_1         ; напровление 0, индекс анимации 1
                FSprite 14,     12,      2,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Dead_0_0         ; напровление 0, индекс анимации 0
._0_1_3         ; t - 0 (), d - 1 (up-right), s - 3 (dead) !
                FSprite 10,      7,      2,      7,      0, PageSprites_0,    MemoryPage_4.SolderA_Dead_1_3         ; напровление 1, индекс анимации 3
                FSprite 10,      8,      2,      7,      0, PageSprites_0,    MemoryPage_4.SolderA_Dead_1_2         ; напровление 1, индекс анимации 2
                FSprite 12,     10,      2,      6,      0, PageSprites_0,    MemoryPage_4.SolderA_Dead_1_1         ; напровление 1, индекс анимации 1
                FSprite 14,     12,      2,      5,      0, PageSprites_0,    MemoryPage_4.SolderA_Dead_1_0         ; напровление 1, индекс анимации 0
._0_2_3         ; t - 0 (), d - 2 (right), s - 3 (dead) !
                FSprite  8,      6,      2,      8,      0, PageSprites_0,    MemoryPage_4.SolderA_Dead_2_3         ; напровление 2, индекс анимации 3
                FSprite  8,      7,      2,      7,      0, PageSprites_0,    MemoryPage_4.SolderA_Dead_2_2         ; напровление 2, индекс анимации 2
                FSprite 10,      9,      2,      8,      0, PageSprites_0,    MemoryPage_4.SolderA_Dead_2_1         ; напровление 2, индекс анимации 1
                FSprite 14,     11,      2,      7,      0, PageSprites_0,    MemoryPage_4.SolderA_Dead_2_0         ; напровление 2, индекс анимации 0
._0_3_3         ; t - 0 (), d - 3 (down-right), s - 3 (dead) !
                FSprite  8,      6,      2,      9,      0, PageSprites_0,    MemoryPage_4.SolderA_Dead_3_3         ; напровление 3, индекс анимации 3
                FSprite 10,      7,      2,      8,      0, PageSprites_0,    MemoryPage_4.SolderA_Dead_3_2         ; напровление 3, индекс анимации 2
                FSprite 14,     13,      2,      8,      0, PageSprites_0,    MemoryPage_4.SolderA_Dead_3_1         ; напровление 3, индекс анимации 1
                FSprite 14,     12,      2,      7,      0, PageSprites_0,    MemoryPage_4.SolderA_Dead_3_0         ; напровление 3, индекс анимации 0
._0_4_3         ; t - 0 (), d - 4 (down), s - 3 (dead) !
                FSprite  8,      5,      2,      8,      0, PageSprites_0,    MemoryPage_4.SolderA_Dead_4_3         ; напровление 4, индекс анимации 3
                FSprite 10,      7,      2,      8,      0, PageSprites_0,    MemoryPage_4.SolderA_Dead_4_2         ; напровление 4, индекс анимации 2
                FSprite 14,     11,      2,      8,      0, PageSprites_0,    MemoryPage_4.SolderA_Dead_4_1         ; напровление 4, индекс анимации 1
                FSprite 14,     12,      2,      7,      0, PageSprites_0,    MemoryPage_4.SolderA_Dead_4_0         ; напровление 4, индекс анимации 0
._0_5_3         ; t - 0 (), d - 4 (down), s - 3 (dead) !
                FSprite  8,      5,      2,      6,      0, PageSprites_0,    MemoryPage_4.SolderA_Dead_5_3         ; напровление 5, индекс анимации 3
                FSprite 10,      7,      2,      6,      0, PageSprites_0,    MemoryPage_4.SolderA_Dead_5_2         ; напровление 5, индекс анимации 2
                FSprite 14,     11,      2,      6,      0, PageSprites_0,    MemoryPage_4.SolderA_Dead_5_1         ; напровление 5, индекс анимации 1
                FSprite 14,     12,      2,      6,      0, PageSprites_0,    MemoryPage_4.SolderA_Dead_5_0         ; напровление 5, индекс анимации 0
._0_6_3         ; t - 0 (), d - 4 (down), s - 3 (dead) !
                FSprite  8,      5,      2,      8,      0, PageSprites_0,    MemoryPage_4.SolderA_Dead_6_3         ; напровление 6, индекс анимации 3
                FSprite  8,      6,      2,      7,      0, PageSprites_0,    MemoryPage_4.SolderA_Dead_6_2         ; напровление 6, индекс анимации 2
                FSprite 10,      8,      2,      6,      0, PageSprites_0,    MemoryPage_4.SolderA_Dead_6_1         ; напровление 6, индекс анимации 1
                FSprite 14,     10,      2,      6,      0, PageSprites_0,    MemoryPage_4.SolderA_Dead_6_0         ; напровление 6, индекс анимации 0
._0_7_3         ; t - 0 (), d - 4 (down), s - 3 (dead) !
                FSprite 10,      6,      2,      6,      0, PageSprites_0,    MemoryPage_4.SolderA_Dead_7_3         ; напровление 7, индекс анимации 3
                FSprite 12,      7,      2,      6,      0, PageSprites_0,    MemoryPage_4.SolderA_Dead_7_2         ; напровление 7, индекс анимации 2
                FSprite 12,      8,      2,      6,      0, PageSprites_0,    MemoryPage_4.SolderA_Dead_7_1         ; напровление 7, индекс анимации 1
                FSprite 14,     11,      2,      7,      0, PageSprites_0,    MemoryPage_4.SolderA_Dead_7_0         ; напровление 7, индекс анимации 0
