
                ifndef _CORE_MODULE_MENU_MAIN_NEW_GAME_ANIMATION_INCLUDE_
                define _CORE_MODULE_MENU_MAIN_NEW_GAME_ANIMATION_INCLUDE_

                module Animation

                include "Core/Include.inc"
                include "LeftFrame/Include.inc"
; Flags:          DB #00

                endmodule

                endif ; ~ _CORE_MODULE_MENU_MAIN_NEW_GAME_ANIMATION_INCLUDE_
