
                ifndef _CORE_MODULE_UNIT_INCLUDE_
                define _CORE_MODULE_UNIT_INCLUDE_

                module Unit

                include "Utils/Include.inc"
                include "Move/Include.inc"
                include "Initialize/Include.inc"
                include "Core/Module/Math/BezierCurve.asm"                      ; мат блок работы с кривыми

                endmodule

                endif ; ~ _CORE_MODULE_UNIT_INCLUDE_
