
                ifndef _CORE_MODULE_ANIMATION_INCLUDE_
                define _CORE_MODULE_ANIMATION_INCLUDE_

                module Animation

                include "../../Animation/AnimationNumberTable.inc"

                include "BlandIdleTurn.asm"
                include "BlandTurn.asm"
                include "BlandMove.asm"
                include "BlandAttack.asm"
                include "BlandDead.asm"
                include "SpriteInfo.asm"
                include "SwitchAnimation.asm"

                endmodule

                endif ; ~_CORE_MODULE_ANIMATION_INCLUDE_
