
                    ; спрайт юнита А смерть (вверх)
SolderA_Dead_0_0:
                    incbin "Sprites/Units/Infantry/Dead/Dead_0_0.spr"            ; 
SolderA_Dead_0_1:
                    incbin "Sprites/Units/Infantry/Dead/Dead_0_1.spr"            ; 
SolderA_Dead_0_2:
                    incbin "Sprites/Units/Infantry/Dead/Dead_0_2.spr"            ; 
SolderA_Dead_0_3:
                    incbin "Sprites/Units/Infantry/Dead/Dead_0_3.spr"            ; 
SolderA_Dead_1_0:
                    incbin "Sprites/Units/Infantry/Dead/Dead_1_0.spr"            ; 
SolderA_Dead_1_1:
                    incbin "Sprites/Units/Infantry/Dead/Dead_1_1.spr"            ; 
SolderA_Dead_1_2:
                    incbin "Sprites/Units/Infantry/Dead/Dead_1_2.spr"            ; 
SolderA_Dead_1_3:
                    incbin "Sprites/Units/Infantry/Dead/Dead_1_3.spr"            ; 
SolderA_Dead_2_0:
                    incbin "Sprites/Units/Infantry/Dead/Dead_2_0.spr"            ; 
SolderA_Dead_2_1:
                    incbin "Sprites/Units/Infantry/Dead/Dead_2_1.spr"            ; 
SolderA_Dead_2_2:
                    incbin "Sprites/Units/Infantry/Dead/Dead_2_2.spr"            ; 
SolderA_Dead_2_3:
                    incbin "Sprites/Units/Infantry/Dead/Dead_2_3.spr"            ; 
SolderA_Dead_3_0:
                    incbin "Sprites/Units/Infantry/Dead/Dead_3_0.spr"            ; 
SolderA_Dead_3_1:
                    incbin "Sprites/Units/Infantry/Dead/Dead_3_1.spr"            ; 
SolderA_Dead_3_2:
                    incbin "Sprites/Units/Infantry/Dead/Dead_3_2.spr"            ; 
SolderA_Dead_3_3:
                    incbin "Sprites/Units/Infantry/Dead/Dead_3_3.spr"            ; 
SolderA_Dead_4_0:
                    incbin "Sprites/Units/Infantry/Dead/Dead_4_0.spr"            ; 
SolderA_Dead_4_1:
                    incbin "Sprites/Units/Infantry/Dead/Dead_4_1.spr"            ; 
SolderA_Dead_4_2:
                    incbin "Sprites/Units/Infantry/Dead/Dead_4_2.spr"            ; 
SolderA_Dead_4_3:
                    incbin "Sprites/Units/Infantry/Dead/Dead_4_3.spr"            ; 
SolderA_Dead_5_0:
                    incbin "Sprites/Units/Infantry/Dead/Dead_5_0.spr"            ; 
SolderA_Dead_5_1:
                    incbin "Sprites/Units/Infantry/Dead/Dead_5_1.spr"            ; 
SolderA_Dead_5_2:
                    incbin "Sprites/Units/Infantry/Dead/Dead_5_2.spr"            ; 
SolderA_Dead_5_3:
                    incbin "Sprites/Units/Infantry/Dead/Dead_5_3.spr"            ; 
SolderA_Dead_6_0:
                    incbin "Sprites/Units/Infantry/Dead/Dead_6_0.spr"            ; 
SolderA_Dead_6_1:
                    incbin "Sprites/Units/Infantry/Dead/Dead_6_1.spr"            ; 
SolderA_Dead_6_2:
                    incbin "Sprites/Units/Infantry/Dead/Dead_6_2.spr"            ; 
SolderA_Dead_6_3:
                    incbin "Sprites/Units/Infantry/Dead/Dead_6_3.spr"            ; 
SolderA_Dead_7_0:
                    incbin "Sprites/Units/Infantry/Dead/Dead_7_0.spr"            ; 
SolderA_Dead_7_1:
                    incbin "Sprites/Units/Infantry/Dead/Dead_7_1.spr"            ; 
SolderA_Dead_7_2:
                    incbin "Sprites/Units/Infantry/Dead/Dead_7_2.spr"            ; 
SolderA_Dead_7_3:
                    incbin "Sprites/Units/Infantry/Dead/Dead_7_3.spr"            ; 
