
                    ; спрайт юнита А атака (вверх)
SolderA_Attack_0_0:
                    incbin "Sprites/Units/SolderA/Attack/Attack_0_0.spr"        ; 
SolderA_Attack_0_1:
                    incbin "Sprites/Units/SolderA/Attack/Attack_0_1.spr"        ; 

                    ; спрайт юнита А атака (вверх-вправо)
SolderA_Attack_1_0:
                    incbin "Sprites/Units/SolderA/Attack/Attack_1_0.spr"        ; 
SolderA_Attack_1_1:
                    incbin "Sprites/Units/SolderA/Attack/Attack_1_1.spr"        ; 

                    ; спрайт юнита А атака (вправо)
SolderA_Attack_2_0:
                    incbin "Sprites/Units/SolderA/Attack/Attack_2_0.spr"        ; 
SolderA_Attack_2_1:
                    incbin "Sprites/Units/SolderA/Attack/Attack_2_1.spr"        ; 

                    ; спрайт юнита А атака (вправо-вниз)
SolderA_Attack_3_0:
                    incbin "Sprites/Units/SolderA/Attack/Attack_3_0.spr"        ; 
SolderA_Attack_3_1:
                    incbin "Sprites/Units/SolderA/Attack/Attack_3_1.spr"        ; 

                    ; спрайт юнита А атака (вниз)
SolderA_Attack_4_0:
                    incbin "Sprites/Units/SolderA/Attack/Attack_4_0.spr"        ; 
SolderA_Attack_4_1:
                    incbin "Sprites/Units/SolderA/Attack/Attack_4_1.spr"        ; 

                    ; спрайт юнита А атака (влево-вниз)
SolderA_Attack_5_0:
                    incbin "Sprites/Units/SolderA/Attack/Attack_5_0.spr"        ; 
SolderA_Attack_5_1:
                    incbin "Sprites/Units/SolderA/Attack/Attack_5_1.spr"        ; 

                    ; спрайт юнита А атака (влево)
SolderA_Attack_6_0:
                    incbin "Sprites/Units/SolderA/Attack/Attack_6_0.spr"        ; 
SolderA_Attack_6_1:
                    incbin "Sprites/Units/SolderA/Attack/Attack_6_1.spr"        ; 

                    ; спрайт юнита А атака (влево-вверх)
SolderA_Attack_7_0:
                    incbin "Sprites/Units/SolderA/Attack/Attack_7_0.spr"        ; 
SolderA_Attack_7_1:
                    incbin "Sprites/Units/SolderA/Attack/Attack_7_1.spr"        ; 