
                ifndef _CORE_MODULE_MENU_MAIN_NEW_GAME_INCLUDE_
                define _CORE_MODULE_MENU_MAIN_NEW_GAME_INCLUDE_

                module NewGame

                include "ChangeMission.asm"
                include "Input.asm"
                include "Room/Include.inc"
                include "Animation/Include.inc"
                include "Message/Include.inc"
                include "Core/Module/VFX/Hologram/Include.inc"

                endmodule

                endif ; ~ _CORE_MODULE_MENU_MAIN_NEW_GAME_INCLUDE_
