
                    ; 0 (Sand 1)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 1 (Sand 2)
                    FSurface SDR_25_PERCENT |   SCF_NONE
                    ; 2 (Sand 3)
                    FSurface SDR_50_PERCENT |   SCF_NONE
                    ; 3 (Sand 4)
                    FSurface SDR_75_PERCENT |   SCF_NONE
                    ; 4 (Grass 1)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 5 (Grass 2)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 6 (Grass 3)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 7 (Grass 4)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 8 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 9 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 10 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 11 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 12 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 13 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 14 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 15 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 16 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 17 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 18 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 19 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 20 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 21 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 22 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 23 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 24 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 25 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 26 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 27 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 28 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 29 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 30 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 31 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 32 (Canyon 1)
                    FSurface SDR_50_PERCENT |   SCF_RIGHT
                    ; 33 (Canyon 2)
                    FSurface SDR_50_PERCENT |   SCF_DOWN
                    ; 34 (Canyon 3)
                    FSurface SDR_50_PERCENT |   SCF_DOWN
                    ; 35 (Canyon 4)
                    FSurface SDR_25_PERCENT |   SCF_DOWN
                    ; 36 (Canyon 5)
                    FSurface SDR_25_PERCENT |   SCF_UP | SCF_LEFT
                    ; 37 (Canyon 6)
                    FSurface SDR_50_PERCENT |   SCF_DOWN | SCF_LEFT
                    ; 38 (Canyon 7)
                    FSurface SDR_50_PERCENT |   SCF_RIGHT
                    ; 39 (Canyon 8)
                    FSurface SDR_0_PERCENT  |   SCF_UP | SCF_RIGHT | SCF_DOWN | SCF_LEFT
                    ; 40 (Canyon 9)
                    FSurface SDR_50_PERCENT |   SCF_LEFT
                    ; 41 (Canyon 10)
                    FSurface SDR_50_PERCENT |   SCF_LEFT
                    ; 42 (Canyon 11)
                    FSurface SDR_0_PERCENT  |   SCF_UP | SCF_LEFT
                    ; 43 (Canyon 12)
                    FSurface SDR_0_PERCENT  |   SCF_DOWN
                    ; 44 (Canyon 13)
                    FSurface SDR_50_PERCENT |   SCF_LEFT
                    ; 45 (Canyon 14)
                    FSurface SDR_50_PERCENT |   SCF_UP | SCF_RIGHT
                    ; 46 (Canyon 15)
                    FSurface SDR_50_PERCENT |   SCF_LEFT
                    ; 47 (Canyon 16)
                    FSurface SDR_50_PERCENT |   SCF_LEFT
                    ; 48 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 49 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 50 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 51 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 52 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 53 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 54 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 55 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 56 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 57 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 58 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 59 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 60 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 61 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 62 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 63 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 64 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 65 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 66 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 67 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 68 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 69 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 70 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 71 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 72 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 73 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 74 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 75 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 76 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 77 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 78 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 79 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 80 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 81 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 82 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 83 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 84 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 85 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 86 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 87 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 88 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 89 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 90 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 91 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 92 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 93 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 94 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 95 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 96 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 97 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 98 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 99 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 100 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 101 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 102 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 103 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 104 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 105 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 106 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 107 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 108 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 109 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 110 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 111 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 112 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 113 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 114 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 115 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 116 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 117 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 118 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 119 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 120 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 121 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 122 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 123 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 124 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 125 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 126 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE
                    ; 127 (-)
                    FSurface SDR_0_PERCENT  |   SCF_NONE