
                ifndef _BUILDER_MENU_PACK_MENU_
                define _BUILDER_MENU_PACK_MENU_

                module Menu

                include "Core/Pack.inc"
                include "Options/Pack.inc"
                include "Main/Pack.inc"
                include "NewGame/Pack.inc"
                include "Graphics/Pack.inc"

                endmodule

                endif ; ~ _BUILDER_MENU_PACK_MENU_

