TankSprite:
                ; Move

._0_1           ; t - 1 (), d - 0 (up), s - 1 (move)
                FSprite 18,     8,      3,      10,      MemoryPage_4.Tank_Move_0_0_S,  PageSprites_0 | FSSF_MASK,  MemoryPage_4.Tank_Move_0_0_M    ; напровление 0, индекс анимации 0
                FSprite 18,     8,      3,      10,      MemoryPage_4.Tank_Move_0_1_S,  PageSprites_0 | FSSF_MASK,  MemoryPage_4.Tank_Move_0_0_M    ; напровление 0, индекс анимации 1
                FSprite 18,     8,      3,      10,      MemoryPage_4.Tank_Move_0_2_S,  PageSprites_0 | FSSF_MASK,  MemoryPage_4.Tank_Move_0_0_M    ; напровление 0, индекс анимации 2

._1_1           ; t - 1 (), d - 1 (up-right), s - 1 (move)
                FSprite 18,     8,      3,      10,      MemoryPage_4.Tank_Move_1_0_S,  PageSprites_0 | FSSF_MASK,  MemoryPage_4.Tank_Move_1_0_M    ; напровление 1, индекс анимации 0
                FSprite 18,     8,      3,      10,      MemoryPage_4.Tank_Move_1_1_S,  PageSprites_0 | FSSF_MASK,  MemoryPage_4.Tank_Move_1_0_M    ; напровление 1, индекс анимации 1
                FSprite 18,     8,      3,      10,      MemoryPage_4.Tank_Move_1_2_S,  PageSprites_0 | FSSF_MASK,  MemoryPage_4.Tank_Move_1_0_M    ; напровление 1, индекс анимации 2


._2_1           ; t - 1 (), d - 2 (right), s - 1 (move)
                FSprite 18,     9,      3,      10,      MemoryPage_4.Tank_Move_2_0_S,  PageSprites_0 | FSSF_MASK,  MemoryPage_4.Tank_Move_2_0_M    ; напровление 2, индекс анимации 0
                FSprite 18,     9,      3,      10,      MemoryPage_4.Tank_Move_2_1_S,  PageSprites_0 | FSSF_MASK,  MemoryPage_4.Tank_Move_2_0_M    ; напровление 2, индекс анимации 1
                FSprite 18,     9,      3,      10,      MemoryPage_4.Tank_Move_2_2_S,  PageSprites_0 | FSSF_MASK,  MemoryPage_4.Tank_Move_2_0_M    ; напровление 2, индекс анимации 2

._3_1           ; t - 1 (), d - 3 (down-right), s - 1 (move)
                FSprite 20,    10,      3,      10,      MemoryPage_4.Tank_Move_3_0_S,  PageSprites_0 | FSSF_MASK,  MemoryPage_4.Tank_Move_3_0_M    ; напровление 3, индекс анимации 0
                FSprite 20,    10,      3,      10,      MemoryPage_4.Tank_Move_3_1_S,  PageSprites_0 | FSSF_MASK,  MemoryPage_4.Tank_Move_3_0_M    ; напровление 3, индекс анимации 1
                FSprite 20,    10,      3,      10,      MemoryPage_4.Tank_Move_3_2_S,  PageSprites_0 | FSSF_MASK,  MemoryPage_4.Tank_Move_3_0_M    ; напровление 3, индекс анимации 2

._4_1           ; t - 1 (), d - 4 (down), s - 1 (move)
                FSprite 18,     8,      3,      10,      MemoryPage_4.Tank_Move_4_0_S,  PageSprites_0 | FSSF_MASK,  MemoryPage_4.Tank_Move_4_0_M    ; напровление 4, индекс анимации 0
                FSprite 18,     8,      3,      10,      MemoryPage_4.Tank_Move_4_1_S,  PageSprites_0 | FSSF_MASK,  MemoryPage_4.Tank_Move_4_0_M    ; напровление 4, индекс анимации 1
                FSprite 18,     8,      3,      10,      MemoryPage_4.Tank_Move_4_2_S,  PageSprites_0 | FSSF_MASK,  MemoryPage_4.Tank_Move_4_0_M    ; напровление 4, индекс анимации 2

._5_1           ; t - 1 (), d - 5 (down-left), s - 1 (move)
                FSprite 20,    10,      3,      10,      MemoryPage_4.Tank_Move_5_0_S,  PageSprites_0 | FSSF_MASK,  MemoryPage_4.Tank_Move_5_0_M    ; напровление 5, индекс анимации 0
                FSprite 20,    10,      3,      10,      MemoryPage_4.Tank_Move_5_1_S,  PageSprites_0 | FSSF_MASK,  MemoryPage_4.Tank_Move_5_0_M    ; напровление 5, индекс анимации 1
                FSprite 20,    10,      3,      10,      MemoryPage_4.Tank_Move_5_2_S,  PageSprites_0 | FSSF_MASK,  MemoryPage_4.Tank_Move_5_0_M    ; напровление 5, индекс анимации 2

._6_1           ; t - 1 (), d - 6 (left), s - 1 (move)
                FSprite 18,     9,      3,      10,      MemoryPage_4.Tank_Move_6_0_S,  PageSprites_0 | FSSF_MASK,  MemoryPage_4.Tank_Move_6_0_M    ; напровление 6, индекс анимации 0
                FSprite 18,     9,      3,      10,      MemoryPage_4.Tank_Move_6_1_S,  PageSprites_0 | FSSF_MASK,  MemoryPage_4.Tank_Move_6_0_M    ; напровление 6, индекс анимации 1
                FSprite 18,     9,      3,      10,      MemoryPage_4.Tank_Move_6_2_S,  PageSprites_0 | FSSF_MASK,  MemoryPage_4.Tank_Move_6_0_M    ; напровление 6, индекс анимации 2

._7_1           ; t - 1 (), d - 7 (up-left), s - 1 (move)
                FSprite 18,     8,      3,      10,      MemoryPage_4.Tank_Move_7_0_S,  PageSprites_0 | FSSF_MASK,  MemoryPage_4.Tank_Move_7_0_M    ; напровление 7, индекс анимации 0
                FSprite 18,     8,      3,      10,      MemoryPage_4.Tank_Move_7_1_S,  PageSprites_0 | FSSF_MASK,  MemoryPage_4.Tank_Move_7_0_M    ; напровление 7, индекс анимации 1
                FSprite 18,     8,      3,      10,      MemoryPage_4.Tank_Move_7_2_S,  PageSprites_0 | FSSF_MASK,  MemoryPage_4.Tank_Move_7_0_M    ; напровление 7, индекс анимации 2

