
                ifndef _CORE_MODULE_DRAW_SPRITE_UNIT_INCLUDE_
                define _CORE_MODULE_DRAW_SPRITE_UNIT_INCLUDE_

                module Sprite

                include "DrawInfantry.asm"
                include "DrawTank.asm"
                include "DrawShuttle.asm"
                include "PrepareSprite.asm"
                include "DrawSpriteUnit.asm"

                endmodule

                endif ; ~ _CORE_MODULE_DRAW_SPRITE_UNIT_INCLUDE_
