
                ifndef _CORE_DISPLAY_METODS_INCLUDE_
                define _CORE_DISPLAY_METODS_INCLUDE_

                module Display

                ; ---------- 8 ----------
                include "8_0.asm"
                include "8_0_Shift.asm"
                include "8_0_LeftShift.asm"
                include "8_0_RightShift.asm"
                ; ---------- 16 ----------
                include "16_0.asm"
                include "16_0_Shift.asm"
                include "16_0_LeftShift.asm"
                include "16_0_RightShift.asm"
                include "16_1_Left.asm"
                include "16_1_Right.asm"
                include "16_1_LeftShift.asm"
                include "16_1_RightShift.asm"
                ; ---------- 24 ----------
                include "24_0.asm"
                include "24_0_Shift.asm"
                include "24_0_LeftShift.asm"
                include "24_0_RightShift.asm"
                include "24_1_Left.asm"
                include "24_1_Right.asm"
                include "24_1_LeftShift.asm"
                include "24_1_RightShift.asm"
                include "24_2_Left.asm"
                include "24_2_Right.asm"
                include "24_2_LeftShift.asm"
                include "24_2_RightShift.asm"
                ; ---------- 32 ----------                          ?

                endmodule

                endif ; ~_CORE_DISPLAY_METODS_INCLUDE_
