
                module Infantry
SpriteInfo:
.MoveUp         FSprite { { 13, 11,  8, 4 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_00 } } ; индекс анимации 0
                FSprite { { 13, 11,  9, 4 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_01 } } ; индекс анимации 1
                FSprite { { 13, 11,  8, 4 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_02 } } ; индекс анимации 2
                FSprite { { 13, 11,  8, 4 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_03 } } ; индекс анимации 3

;                 FSprite     16-2, 8-1+4, 1,  4, 0,  Page.Graphics.Pack1, Sprites.Infantry.Move_00   ; напровление 0, индекс анимации 3
;                 FSprite     16-2, 8-1+4, 1,  4, 0,  Page.Graphics.Pack1, Sprites.Infantry.Move_01   ; напровление 0, индекс анимации 2
;                 FSprite     16-2, 8-1+4, 2, 12, 0,  Page.Graphics.Pack1, Sprites.Infantry.Move_02   ; напровление 0, индекс анимации 1
;                 FSprite     16-2, 8-1+4, 1,  4, 0,  Page.Graphics.Pack1, Sprites.Infantry.Move_03   ; напровление 0, индекс анимации 0

; .MoveUpRight    FSprite 16-2,     8-1+4,      2,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_1_3   ; напровление 1, индекс анимации 3
;                 FSprite 16-2,     8-1+4,      2,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_1_2   ; напровление 1, индекс анимации 2
;                 FSprite 16-4,     8-1+4,      2,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_1_1   ; напровление 1, индекс анимации 1
;                 FSprite 16-2,     8-1+4,      2,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_1_0   ; напровление 1, индекс анимации 0

; .MoveRight      FSprite 16-2,     8-1+4,      2,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_2_3   ; напровление 2, индекс анимации 3
;                 FSprite 16-2,     8-1+4,      2,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_2_2   ; напровление 2, индекс анимации 2
;                 FSprite 16-2,     8-1+4,      2,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_2_1   ; напровление 2, индекс анимации 1
;                 FSprite 16-2,     8-1+4,      2,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_2_0   ; напровление 2, индекс анимации 0

; .MoveDownRight  FSprite 16-2,     8-1+4,      1,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_3_3   ; напровление 3, индекс анимации 3
;                 FSprite 16-2,     8-1+4,      1,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_3_2   ; напровление 3, индекс анимации 2
;                 FSprite 16-2,     8-1+4,      1,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_3_1   ; напровление 3, индекс анимации 1
;                 FSprite 16-2,     8-1+4,      1,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_3_0   ; напровление 3, индекс анимации 0

; .MoveDown       FSprite 16-2,     8-1+4,      1,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_4_3   ; напровление 4, индекс анимации 3
;                 FSprite 16-2,     8-1+4,      1,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_4_2   ; напровление 4, индекс анимации 2
;                 FSprite 16-2,     8-1+4,      1,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_4_1   ; напровление 4, индекс анимации 1
;                 FSprite 16-2,     8-1+4,      1,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_4_0   ; напровление 4, индекс анимации 0

; .MoveDownLeft   FSprite 16-2,     8-1+4,      2,     12,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_5_3   ; напровление 5, индекс анимации 3
;                 FSprite 16-2,     8-1+4,      2,     12,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_5_2   ; напровление 5, индекс анимации 2
;                 FSprite 16-2,     8-1+4,      2,     12,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_5_1   ; напровление 5, индекс анимации 1
;                 FSprite 16-2,     8-1+4,      2,     12,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_5_0   ; напровление 5, индекс анимации 0

; .MoveLeft       FSprite 16-2,     8-1+4,      2,     12,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_6_3   ; напровление 6, индекс анимации 3
;                 FSprite 16-2,     8-1+4,      2,     12,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_6_2   ; напровление 6, индекс анимации 2
;                 FSprite 16-2,     8-1+4,      2,     12,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_6_1   ; напровление 6, индекс анимации 1
;                 FSprite 16-2,     8-1+4,      2,     12,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_6_0   ; напровление 6, индекс анимации 0

; .MoveUpLeft     FSprite 16-2,     8-1+4,      1,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_7_3   ; напровление 7, индекс анимации 3
;                 FSprite 16-2,     8-1+4,      1,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_7_2   ; напровление 7, индекс анимации 2
;                 FSprite 16-4,     8-1+4,      1,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_7_1   ; напровление 7, индекс анимации 1
;                 FSprite 16-2,     8-1+4,      1,      4,      0, PageSprites_0,    MemoryPage_4.SolderA_Move_7_0   ; напровление 7, индекс анимации 0

                endmodule
