
                module Infantry

                ; вверх
Move_00:        incbin "Core/Module/Sprites/Infantry/Move/Move_0_0.spr"
Move_01:        incbin "Core/Module/Sprites/Infantry/Move/Move_0_1.spr"
Move_02:        incbin "Core/Module/Sprites/Infantry/Move/Move_0_2.spr"
Move_03:        incbin "Core/Module/Sprites/Infantry/Move/Move_0_3.spr"
                ; вверх-вправо
Move_10:        incbin "Core/Module/Sprites/Infantry/Move/Move_1_0.spr"
Move_11:        incbin "Core/Module/Sprites/Infantry/Move/Move_1_1.spr"
Move_12:        incbin "Core/Module/Sprites/Infantry/Move/Move_1_2.spr"
Move_13:        incbin "Core/Module/Sprites/Infantry/Move/Move_1_3.spr"
                ; вправо
Move_20:        incbin "Core/Module/Sprites/Infantry/Move/Move_2_0.spr"
Move_21:        incbin "Core/Module/Sprites/Infantry/Move/Move_2_1.spr"
Move_22:        incbin "Core/Module/Sprites/Infantry/Move/Move_2_2.spr"
Move_23:        incbin "Core/Module/Sprites/Infantry/Move/Move_2_3.spr"
                ; вправо-вниз
Move_30:        incbin "Core/Module/Sprites/Infantry/Move/Move_3_0.spr"
Move_31:        incbin "Core/Module/Sprites/Infantry/Move/Move_3_1.spr"
Move_32:        incbin "Core/Module/Sprites/Infantry/Move/Move_3_2.spr"
Move_33:        incbin "Core/Module/Sprites/Infantry/Move/Move_3_3.spr"
                ; вниз
Move_40:        incbin "Core/Module/Sprites/Infantry/Move/Move_4_0.spr"
Move_41:        incbin "Core/Module/Sprites/Infantry/Move/Move_4_1.spr"
Move_42:        incbin "Core/Module/Sprites/Infantry/Move/Move_4_2.spr"
Move_43:        incbin "Core/Module/Sprites/Infantry/Move/Move_4_3.spr"
                ; влево-вниз
Move_50:        incbin "Core/Module/Sprites/Infantry/Move/Move_5_0.spr"
Move_51:        incbin "Core/Module/Sprites/Infantry/Move/Move_5_1.spr"
Move_52:        incbin "Core/Module/Sprites/Infantry/Move/Move_5_2.spr"
Move_53:        incbin "Core/Module/Sprites/Infantry/Move/Move_5_3.spr"
                ; влево
Move_60:        incbin "Core/Module/Sprites/Infantry/Move/Move_6_0.spr"
Move_61:        incbin "Core/Module/Sprites/Infantry/Move/Move_6_1.spr"
Move_62:        incbin "Core/Module/Sprites/Infantry/Move/Move_6_2.spr"
Move_63:        incbin "Core/Module/Sprites/Infantry/Move/Move_6_3.spr"
                ; влево-вверх
Move_70:        incbin "Core/Module/Sprites/Infantry/Move/Move_7_0.spr"
Move_71:        incbin "Core/Module/Sprites/Infantry/Move/Move_7_1.spr"
Move_72:        incbin "Core/Module/Sprites/Infantry/Move/Move_7_2.spr"
Move_73:        incbin "Core/Module/Sprites/Infantry/Move/Move_7_3.spr"

                endmodule
