
                module Infantry
SpriteInfo:
                FSprite { { 13, -3,  8,  4 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_00 } }    ; индекс анимации 0 (up)
                FSprite { { 13, -3, 10,  4 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_10 } }    ; индекс анимации 0 (up-right)
                FSprite { { 13, -3,  9,  4 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_20 } }    ; индекс анимации 0 (right)
                FSprite { { 14, -3,  8,  4 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_30 } }    ; индекс анимации 0 (down-right)
                FSprite { { 14, -3,  8,  4 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_40 } }    ; индекс анимации 0 (down)
                FSprite { { 13, -3, 10, -4 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_50 } }    ; индекс анимации 0 (down-left)
                FSprite { { 13, -3,  9, -4 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_60 } }    ; индекс анимации 0 (left)
                FSprite { { 13, -3,  8,  4 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_70 } }    ; индекс анимации 0 (up-left)

                FSprite { { 13, 11,  9, 12 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_01 } }    ; индекс анимации 1 (up)
                FSprite { { 12, 11,  8,  3 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_11 } }    ; индекс анимации 1 (up-right)
                FSprite { { 13, 11,  8,  3 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_21 } }    ; индекс анимации 1 (right)
                FSprite { { 13, 11,  8,  4 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_31 } }    ; индекс анимации 1 (down-right)
                FSprite { { 14, 11,  8,  4 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_41 } }    ; индекс анимации 1 (down)
                FSprite { { 13, 11, 10, 12 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_51 } }    ; индекс анимации 1 (down-left)
                FSprite { { 13, 11,  9, 12 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_61 } }    ; индекс анимации 1 (left)
                FSprite { { 12, 11,  8,  4 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_71 } }    ; индекс анимации 1 (up-left)

                FSprite { { 13, 11,  8,  4 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_02 } }    ; индекс анимации 2 (up)
                FSprite { { 14, 11, 10,  4 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_12 } }    ; индекс анимации 2 (up-right)
                FSprite { { 14, 11,  9,  4 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_22 } }    ; индекс анимации 2 (right)
                FSprite { { 14, 11,  8,  4 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_32 } }    ; индекс анимации 2 (down-right)
                FSprite { { 14, 11,  8,  4 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_42 } }    ; индекс анимации 2 (down)
                FSprite { { 14, 11, 10, 12 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_52 } }    ; индекс анимации 2 (down-left)
                FSprite { { 14, 11,  9, 12 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_62 } }    ; индекс анимации 2 (left)
                FSprite { { 14, 11,  8,  4 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_72 } }    ; индекс анимации 2 (up-left)

                FSprite { { 13, 11,  8,  4 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_03 } }    ; индекс анимации 3 (up)
                FSprite { { 13, 11, 10,  4 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_13 } }    ; индекс анимации 3 (up-right)
                FSprite { { 13, 11,  9,  4 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_23 } }    ; индекс анимации 3 (right)
                FSprite { { 13, 11,  8,  4 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_33 } }    ; индекс анимации 3 (down-right)
                FSprite { { 14, 11,  8,  4 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_43 } }    ; индекс анимации 3 (down)
                FSprite { { 13, 11,  8,  4 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_53 } }    ; индекс анимации 3 (down-left)
                FSprite { { 13, 11,  8,  4 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_63 } }    ; индекс анимации 3 (left)
                FSprite { { 13, 11,  8,  4 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Infantry.Move_73 } }    ; индекс анимации 3 (up-left)

                endmodule
