
                ifndef _CORE_AI_BEHAVIOR_TASK_INDICES_INCLUDE_
                define _CORE_AI_BEHAVIOR_TASK_INDICES_INCLUDE_
BTT_IDLE        EQU 0x00                                                        ; Idle
BTT_WP          EQU 0x01                                                        ; WayPoint
BTT_TTO         EQU 0x02                                                        ; TurnTo
BTT_MTO         EQU 0x03                                                        ; MoveTo
BTT_ATO         EQU 0x04                                                        ; AttackTo
BTT_CE          EQU 0x05                                                        ; CheckEnemy

                endif ; ~ _CORE_AI_BEHAVIOR_TASK_INDICES_INCLUDE_