                    ; спрайт танка (вверх)
Tank_Move_0_0:
                    incbin "Sprites/Units/Tank/Move/Move_0_0.spr"               ; 
Tank_Move_0_0_M:    EQU Tank_Move_0_0 + 53                                      ; адрес маски
Tank_Move_0_0_S:    EQU 54                                                      ; смещение от маски 1 спрайта
Tank_Move_0_1_S:    EQU 108                                                     ; смещение от маски 2 спрайта
Tank_Move_0_2_S:    EQU 162                                                     ; смещение от маски 3 спрайта
