
                module Cursor
SpriteInfo:
                FSprite { { 13,  0, 10,  0 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Cursor.Base_0 } }       ; индекс анимации 0
                FSprite { { 12,  0,  9,  0 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Cursor.Base_1 } }       ; индекс анимации 1
                FSprite { { 11,  0,  8,  0 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Cursor.Base_2 } }       ; индекс анимации 2
                FSprite { {  9,  0,  7,  0 }, 0, { Page.Graphics.Pack1, Graphics.Spites.Cursor.Base_3 } }       ; индекс анимации 3

                endmodule
