
                module Cursor
SpriteInfo:
                FSprite { { 13,  0, 10,  0 }, 0, { 0, Game.Cursor.Base_0 } }    ; индекс анимации 0
                FSprite { { 12,  0,  9,  0 }, 0, { 0, Game.Cursor.Base_1 } }    ; индекс анимации 1
                FSprite { { 11,  0,  8,  0 }, 0, { 0, Game.Cursor.Base_2 } }    ; индекс анимации 2
                FSprite { { 10,  0,  7,  0 }, 0, { 0, Game.Cursor.Base_3 } }    ; индекс анимации 3

                endmodule
