
                ifndef _CORE_MODULE_MENU_MAIN_INCLUDE_
                define _CORE_MODULE_MENU_MAIN_INCLUDE_

                module Main

                include "Const.inc"
                include "Main.asm"
                include "Fadein.asm"
                include "Fadeout.asm"
                include "MainLoadText.asm"
                include "InterruptHandler.asm"
                include "Select.asm"
                include "Input.asm"
                include "../../VFX/Include.inc"

                endmodule

                endif ; ~ _CORE_MODULE_MENU_MAIN_INCLUDE_
