
                ifndef _CORE_MODULE_MENU_MAIN_INCLUDE_
                define _CORE_MODULE_MENU_MAIN_INCLUDE_

                module Main

                include "Main.asm"
                include "MainLoadText.asm"
                include "InterruptHandler.asm"
                include "../../VFX/Include.inc"

                endmodule

                endif ; ~ _CORE_MODULE_MENU_MAIN_INCLUDE_
