
                ifndef _CORE_MODULE_AI_INCLUDE_
                define _CORE_MODULE_AI_INCLUDE_

                module AI

                include "Base.asm"
                include "Composite/Include.inc"
                include "Task/Include.inc"
                include "Behavior/Control.asm"
                include "Behavior/Handler.asm"

                endmodule

                endif ; ~ _CORE_MODULE_AI_INCLUDE_