
                ifndef _CORE_MODULE_TABLE_GRAPHICS_TILEMAP_PACK_1_
                define _CORE_MODULE_TABLE_GRAPHICS_TILEMAP_PACK_1_
Water:          incbin "Core/Module/Sprites/Tilemap/Pack 1/Water/Water.spr"
                incbin "Core/Module/Sprites/Tilemap/Pack 1/Water/WaterReflections_1_1.spr"
                incbin "Core/Module/Sprites/Tilemap/Pack 1/Water/WaterReflections_1_0.spr"
Coast_0011:     incbin "Core/Module/Sprites/Tilemap/Pack 1/Coast/Coast_3.spr"
Coast_0110:     incbin "Core/Module/Sprites/Tilemap/Pack 1/Coast/Coast_1.spr"
Coast_0111:     incbin "Core/Module/Sprites/Tilemap/Pack 1/Coast/Coast_0.spr"
Coast_1001:     incbin "Core/Module/Sprites/Tilemap/Pack 1/Coast/Coast_6.spr"
Coast_1011:     incbin "Core/Module/Sprites/Tilemap/Pack 1/Coast/Coast_5.spr"
Coast_1100:     incbin "Core/Module/Sprites/Tilemap/Pack 1/Coast/Coast_4.spr"
Coast_1101:     incbin "Core/Module/Sprites/Tilemap/Pack 1/Coast/Coast_7.spr"
Coast_1110:     incbin "Core/Module/Sprites/Tilemap/Pack 1/Coast/Coast_2.spr"

Ground_0:       incbin "Core/Module/Sprites/Tilemap/Pack 1/Ground/Sand_0.spr"
Ground_1:       incbin "Core/Module/Sprites/Tilemap/Pack 1/Ground/Sand_1.spr"
Ground_2:       incbin "Core/Module/Sprites/Tilemap/Pack 1/Ground/Sand_2.spr"
Ground_3:       incbin "Core/Module/Sprites/Tilemap/Pack 1/Ground/Sand_3.spr"
Ground_4:       incbin "Core/Module/Sprites/Tilemap/Pack 1/Ground/Sand_4.spr"
Ground_5:       incbin "Core/Module/Sprites/Tilemap/Pack 1/Ground/Sand_5.spr"
Ground_6:       incbin "Core/Module/Sprites/Tilemap/Pack 1/Ground/Sand_6.spr"
Ground_7:       incbin "Core/Module/Sprites/Tilemap/Pack 1/Ground/Sand_7.spr"

                endif ; ~ _CORE_MODULE_TABLE_GRAPHICS_TILEMAP_PACK_1_
