
                ifndef _STRUCTURE_AABB_
                define _STRUCTURE_AABB_

; axis aligned bounding box

                struct FAABB
Y               FValue                                                          ; maxY (L), minY (H)
X               FValue                                                          ; maxX (L), minX (H)
                ends

                endif ; ~_STRUCTURE_AABB_
