
                ifndef _STRUCT_INCLUDE_
                define _STRUCT_INCLUDE_

                include "Base.inc"
                include "AABB.inc"
                include "Config.inc"
                include "Game.inc"

                include "Sprite.inc"
                include "Animation.inc"
                include "Surface.inc"
                include "AnimTile.inc"
                include "BehaviorTree.inc"
                include "Unit.inc"

                include "Files.inc"
                include "FileSystemVaribles.inc"

                include "Dialog.inc"

                include "Level.inc"

                endif ; ~_STRUCT_INCLUDE_
