
                    ; спрайт танка атака (вверх)
Tank_Attack_0_0:
                    incbin "Sprites/Units/Tank/Turn/Turn_0_0.spr"               ; 
Tank_Attack_0_1:
                    incbin "Sprites/Units/Tank/Attack/Attack_0_0.spr"           ; 
Tank_Attack_0_2:
                    incbin "Sprites/Units/Tank/Attack/Attack_0_1.spr"           ; 

                    ; спрайт танка атака (вверх-вправо)
Tank_Attack_1_0:
                    incbin "Sprites/Units/Tank/Turn/Turn_1_0.spr"               ; 
Tank_Attack_1_1:
                    incbin "Sprites/Units/Tank/Attack/Attack_1_0.spr"           ; 
Tank_Attack_1_2:
                    incbin "Sprites/Units/Tank/Attack/Attack_1_1.spr"           ; 

                    ; спрайт танка атака (вправо)
Tank_Attack_2_0:
                    incbin "Sprites/Units/Tank/Turn/Turn_2_0.spr"               ; 
Tank_Attack_2_1:
                    incbin "Sprites/Units/Tank/Attack/Attack_2_0.spr"           ; 
Tank_Attack_2_2:
                    incbin "Sprites/Units/Tank/Attack/Attack_2_1.spr"           ; 

                    ; спрайт танка атака (вправо-вниз)
Tank_Attack_3_0:
                    incbin "Sprites/Units/Tank/Turn/Turn_3_0.spr"               ; 
Tank_Attack_3_1:
                    incbin "Sprites/Units/Tank/Attack/Attack_3_0.spr"           ; 
Tank_Attack_3_2:
                    incbin "Sprites/Units/Tank/Attack/Attack_3_1.spr"           ; 

                    ; спрайт танка атака (вниз)
Tank_Attack_4_0:
                    incbin "Sprites/Units/Tank/Turn/Turn_4_0.spr"               ; 
Tank_Attack_4_1:
                    incbin "Sprites/Units/Tank/Attack/Attack_4_0.spr"           ; 
Tank_Attack_4_2:
                    incbin "Sprites/Units/Tank/Attack/Attack_4_1.spr"           ; 

                    ; спрайт танка атака (влево-вниз)
Tank_Attack_5_0:
                    incbin "Sprites/Units/Tank/Turn/Turn_5_0.spr"               ; 
Tank_Attack_5_1:
                    incbin "Sprites/Units/Tank/Attack/Attack_5_0.spr"           ; 
Tank_Attack_5_2:
                    incbin "Sprites/Units/Tank/Attack/Attack_5_1.spr"           ; 

                    ; спрайт танка атака (влево)
Tank_Attack_6_0:
                    incbin "Sprites/Units/Tank/Turn/Turn_6_0.spr"               ; 
Tank_Attack_6_1:
                    incbin "Sprites/Units/Tank/Attack/Attack_6_0.spr"           ; 
Tank_Attack_6_2:
                    incbin "Sprites/Units/Tank/Attack/Attack_6_1.spr"           ; 

                    ; спрайт танка атака (влево-вверх)
Tank_Attack_7_0:
                    incbin "Sprites/Units/Tank/Turn/Turn_7_0.spr"               ; 
Tank_Attack_7_1:
                    incbin "Sprites/Units/Tank/Attack/Attack_7_0.spr"           ; 
Tank_Attack_7_2:
                    incbin "Sprites/Units/Tank/Attack/Attack_7_1.spr"           ; 
