                    ; спрайт танка (вверх)
Tank_Move_0_0:
                    incbin "Sprites/Units/Tank/Move/Move_0_0.spr"               ; 
Tank_Move_0_0_M:    EQU Tank_Move_0_0 + 53                                      ; адрес маски
Tank_Move_0_0_S:    EQU 54                                                      ; смещение от маски 1 спрайта
Tank_Move_0_1_S:    EQU 108                                                     ; смещение от маски 2 спрайта
Tank_Move_0_2_S:    EQU 162                                                     ; смещение от маски 3 спрайта

                    ; спрайт танка (вверх-вправо)
Tank_Move_1_0:
                    incbin "Sprites/Units/Tank/Move/Move_1_0.spr"               ; 
Tank_Move_1_0_M:    EQU Tank_Move_1_0 + 53                                      ; адрес маски
Tank_Move_1_0_S:    EQU 54                                                      ; смещение от маски 1 спрайта
Tank_Move_1_1_S:    EQU 108                                                     ; смещение от маски 2 спрайта
Tank_Move_1_2_S:    EQU 162                                                     ; смещение от маски 3 спрайта

                    ; спрайт танка (вправо)
Tank_Move_2_0:
                    incbin "Sprites/Units/Tank/Move/Move_2_0.spr"               ; 
Tank_Move_2_0_M:    EQU Tank_Move_2_0 + 53                                      ; адрес маски
Tank_Move_2_0_S:    EQU 54                                                      ; смещение от маски 1 спрайта
Tank_Move_2_1_S:    EQU 108                                                     ; смещение от маски 2 спрайта
Tank_Move_2_2_S:    EQU 162                                                     ; смещение от маски 3 спрайта

                    ; спрайт танка (вправо-вниз)
Tank_Move_3_0:
                    incbin "Sprites/Units/Tank/Move/Move_3_0.spr"               ; 
Tank_Move_3_0_M:    EQU Tank_Move_3_0 + 59                                      ; адрес маски
Tank_Move_3_0_S:    EQU 60                                                      ; смещение от маски 1 спрайта
Tank_Move_3_1_S:    EQU 120                                                     ; смещение от маски 2 спрайта
Tank_Move_3_2_S:    EQU 180                                                     ; смещение от маски 3 спрайта

                    ; спрайт танка (вниз)
Tank_Move_4_0:
                    incbin "Sprites/Units/Tank/Move/Move_4_0.spr"               ; 
Tank_Move_4_0_M:    EQU Tank_Move_4_0 + 53                                      ; адрес маски
Tank_Move_4_0_S:    EQU 54                                                      ; смещение от маски 1 спрайта
Tank_Move_4_1_S:    EQU 108                                                     ; смещение от маски 2 спрайта
Tank_Move_4_2_S:    EQU 162                                                     ; смещение от маски 3 спрайта

                    ; спрайт танка (влево-вниз)
Tank_Move_5_0:
                    incbin "Sprites/Units/Tank/Move/Move_5_0.spr"               ; 
Tank_Move_5_0_M:    EQU Tank_Move_5_0 + 59                                      ; адрес маски
Tank_Move_5_0_S:    EQU 60                                                      ; смещение от маски 1 спрайта
Tank_Move_5_1_S:    EQU 120                                                     ; смещение от маски 2 спрайта
Tank_Move_5_2_S:    EQU 180                                                     ; смещение от маски 3 спрайта

                    ; спрайт танка (влево)
Tank_Move_6_0:
                    incbin "Sprites/Units/Tank/Move/Move_6_0.spr"               ; 
Tank_Move_6_0_M:    EQU Tank_Move_6_0 + 53                                      ; адрес маски
Tank_Move_6_0_S:    EQU 54                                                      ; смещение от маски 1 спрайта
Tank_Move_6_1_S:    EQU 108                                                     ; смещение от маски 2 спрайта
Tank_Move_6_2_S:    EQU 162                                                     ; смещение от маски 3 спрайта

                    ; спрайт танка (влево-вверх)
Tank_Move_7_0:
                    incbin "Sprites/Units/Tank/Move/Move_7_0.spr"               ; 
Tank_Move_7_0_M:    EQU Tank_Move_7_0 + 53                                      ; адрес маски
Tank_Move_7_0_S:    EQU 54                                                      ; смещение от маски 1 спрайта
Tank_Move_7_1_S:    EQU 108                                                     ; смещение от маски 2 спрайта
Tank_Move_7_2_S:    EQU 162                                                     ; смещение от маски 3 спрайта
