
                ifndef _TILEMAP_TEST_SURFACE_
                define _TILEMAP_TEST_SURFACE_

                ; 0 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE    |   SCF_NOT_ANIM
                ; 1 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE    |   SCF_NOT_ANIM
                ; 2 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE    |   SCF_NOT_ANIM
                ; 3 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE    |   SCF_NOT_ANIM
                ; 4 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE    |   SCF_NOT_ANIM
                ; 5 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE    |   SCF_NOT_ANIM
                ; 6 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE    |   SCF_NOT_ANIM
                ; 7 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE    |   SCF_NOT_ANIM
                ; 8 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE    |   SCF_NOT_ANIM
                ; 9 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE    |   SCF_NOT_ANIM
                ; 10 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE    |   SCF_NOT_ANIM
                ; 11 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE    |   SCF_NOT_ANIM
                ; 12 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE    |   SCF_NOT_ANIM
                ; 13 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE    |   SCF_NOT_ANIM
                ; 14 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE    |   SCF_NOT_ANIM
                ; 15 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE    |   SCF_NOT_ANIM
                ; 16 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE    |   SCF_NOT_ANIM
                ; 17 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE    |   SCF_NOT_ANIM
                ; 18 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE    |   SCF_NOT_ANIM
                ; 19 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE    |   SCF_NOT_ANIM
                ; 20 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE    |   SCF_NOT_ANIM
                ; 21 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE    |   SCF_NOT_ANIM
                ; 22 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE    |   SCF_NOT_ANIM
                ; 23 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE    |   SCF_NOT_ANIM
                ; 24 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE    |   SCF_NOT_ANIM
                ; 25 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE    |   SCF_NOT_ANIM
                ; 26 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE    |   SCF_NOT_ANIM
                ; 27 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE    |   SCF_NOT_ANIM
                ; 28 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE    |   SCF_NOT_ANIM
                ; 29 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE    |   SCF_NOT_ANIM
                ; 30 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE    |   SCF_NOT_ANIM
                ; 31 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE    |   SCF_NOT_ANIM
                ; 32 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 33 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 34 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 35 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 36 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 37 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 38 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 39 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 40 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 41 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 42 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 43 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 44 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 45 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 46 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 47 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 48 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 49 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 50 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 51 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 52 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 53 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 54 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 55 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 56 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 57 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 58 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 59 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 60 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 61 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 62 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 63 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 64 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 65 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 66 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 67 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 68 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 69 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 70 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 71 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 72 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 73 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 74 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 75 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 76 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 77 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 78 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 79 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 80 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 81 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 82 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 83 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 84 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 85 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 86 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 87 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 88 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 89 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 90 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 91 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 92 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 93 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 94 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 95 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 96 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 97 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 98 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 99 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 100 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 101 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 102 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 103 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 104 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 105 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 106 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 107 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 108 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 109 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 110 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 111 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 112 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 113 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 114 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 115 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 116 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 117 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 118 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 119 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 120 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 121 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 122 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 123 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 124 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 125 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 126 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE
                ; 127 (-)
                FSurface SDR_0_PERCENT  |   SCF_NONE

                endif ; ~_TILEMAP_TEST_SURFACE_
