
                ifndef _CORE_MODULE_UTILS_UNIT_INCLUDE_MEMORY_PAGE_0_
                define _CORE_MODULE_UTILS_UNIT_INCLUDE_MEMORY_PAGE_0_

                module Unit

                include "CalculateDirectionRotation.asm"
                include "GetScreenAABB.asm"
                include "GetAddressInTable.asm""
                include "GetUnitsListInLocation.asm"
                include "Shot/Include.inc"
                include "State/CheckState.asm"
                include "State/SetState.asm"

                endmodule

                endif ; ~ _CORE_MODULE_UTILS_UNIT_INCLUDE_MEMORY_PAGE_0_
