
                ifndef _CORE_MODULE_UTILS_INCLUDE_MEMORY_PAGE_0_
                define _CORE_MODULE_UTILS_INCLUDE_MEMORY_PAGE_0_

                module Utils

                include "Unit/Include_MemPage0.inc"

                include "Unit/Visibility/CheckRadius.asm"
                include "Unit/Visibility/GetListUnits.asm"

                endmodule

                endif ; ~ _CORE_MODULE_UTILS_INCLUDE_MEMORY_PAGE_0_
