
                ifndef _CORE_MODULE_AI_TASK_TABLE_
                define _CORE_MODULE_AI_TASK_TABLE_
Table:          DW BTT.Idle                                                     ; BTT_IDLE
                DW BTT.WayPoint                                                 ; BTT_WP
                DW BTT.TurnTo                                                   ; BTT_TTO
                DW BTT.MoveTo                                                   ; BTT_MTO
                DW BTT.AttackTo                                                 ; BTT_ATO
                DW BTT.CheckEnemy                                               ; BTT_CE

                endif ; ~ _CORE_MODULE_AI_TASK_TABLE_