;   000 - 1A (первый тир, нейтрального шаттла)
Shuttle_1A:     FCompositeSpriteInfo 16, -16, 16, -16, CSIF_SIZE_32 | CSIF_OR_XOR | CSIF_ANIM_2
                incbin "Core/Module/Sprites/Tilemap/Pack 1/Foliage/Dracunculus_0.spr"
                incbin "Core/Module/Sprites/Tilemap/Pack 1/Foliage/Dracunculus_1.spr"

                FCompositeSpriteInfo 16,   0, 16, -16, CSIF_SIZE_32 | CSIF_OR | CSIF_ANIM_NONE
                incbin "Core/Module/Sprites/Tilemap/Pack 1/Foliage/Dracunculus_2.spr"

                FCompositeSpriteInfo 16,  16, 16, -16, CSIF_SIZE_32 | CSIF_OR_XOR | CSIF_ANIM_2
                incbin "Core/Module/Sprites/Tilemap/Pack 1/Foliage/Dracunculus_3.spr"
                incbin "Core/Module/Sprites/Tilemap/Pack 1/Foliage/Dracunculus_4.spr"

                FCompositeSpriteInfo 32,   0, 16, -16, CSIF_SIZE_64 | CSIF_OR_XOR | CSIF_ANIM_NONE
                incbin "Core/Module/Sprites/Tilemap/Pack 1/Foliage/Dracunculus_3.spr"

                FCompositeSpriteInfo 32,   0, 16,   0, CSIF_SIZE_64 | CSIF_OR | CSIF_ANIM_NONE
                incbin "Core/Module/Sprites/Tilemap/Pack 1/Foliage/Dracunculus_3.spr"

                FCompositeSpriteInfo 32,   0, 16,  16, CSIF_SIZE_64 | CSIF_OR | CSIF_ANIM_NONE
                incbin "Core/Module/Sprites/Tilemap/Pack 1/Foliage/Dracunculus_4.spr"
