
                ifndef _CORE_MODULE_VFX_HOLOGRAM_INCLUDE_
                define _CORE_MODULE_VFX_HOLOGRAM_INCLUDE_

                module Hologram
Begin:          EQU $
                include "Struct.inc"

                display " - Hologram : \t\t\t\t, /A, Begin, " = busy [ ", /D, $ - Begin, " bytes  ]"

                endmodule

                endif ; ~ _CORE_MODULE_VFX_HOLOGRAM_INCLUDE_
